    
language: go

go:
  - 1.13.x
  - master


dist: bionic # ubuntu 18.04


script:
  - make init
  - make build-linux
  - ls bin
  - echo $PATH
  - cp bin/fileboy-linux-amd64.bin /home/travis/bin/fileboy
  - fileboy version
  - fileboy help
  - fileboy init
  - cat filegirl.yaml
  - fileboy exec
  - fileboy deamon
  - cat .fileboy.pid
  - fileboy stop

