    
language: go

go:
  - 1.13.x
  - master


dist: bionic # ubuntu 18.04


script:
  - make init
  - make build-linux
  - ls bin
  - ./bin/fileboy-linux-amd64.bin version
  - ./bin/fileboy-linux-amd64.bin help
  - ./bin/fileboy-linux-amd64.bin init
  - cat filegirl.yaml
  - ./bin/fileboy-linux-amd64.bin exec

